### ISSUE TITLE
Google Pay missing as payment method

### ISSUE THREAD

**Issue by neo1992** [Viincenttt/MollieApi#408]
Google Pay is not available in Mollie.Api.Models.Payment.PaymentMethod

**Comment by Viincenttt** [comment]
Hi @neo1992 

Thanks! Do you happen to know what the exact name of the payment method is that the Mollie API uses for Google pay? I don't see it mentioned on the "Create payment" API documentation: https://docs.mollie.com/reference/create-payment. 

![image](https://github.com/user-attachments/assets/4c9bd7ac-0740-4572-a1dd-2e42d28b64d1)

**Comment by neo1992** [comment]
Hi @Viincenttt I do not. I just see a Google Pay option under website profiles, but don't know how to offer it to customers
![Screenshot 2024-11-19 160208](https://github.com/user-attachments/assets/fa74e410-b56e-489e-9442-3a7df4875dfb)

**Comment by Viincenttt** [comment]
I've just merged a PR to add the payment method to the list of constant strings :) I'll release it soon, but in the mean while you can create a payment with Method = "googlepay".

**Comment by Viincenttt** [comment]
The Google Pay payment method has been added in version 4.5.0.0

**Comment by neo1992** [comment]
Updated to 4.5.0.0, have had Google Pay enabled in Mollie for weeks. With this code I get error

"Exception Details: Mollie.Api.Client.MollieApiException: Internal Server Error - Internal Server Error"

On codeline:

`Dim paymentResponse As PaymentResponse = Await paymentClient.CreatePaymentAsync(paymentRequest)`

Codeblock:

```
        Dim mollieCurrency As String = "EUR"
        mollieCurrency = Currency.EUR

        Dim paymentClient As IPaymentClient
		paymentClient = New PaymentClient(ConfigurationManager.AppSettings("mollie_api_testkey"), New HttpClient())

        Dim paymentRequest As New PaymentRequest() With {
                    .Amount = New Amount(mollieCurrency, priceInclTaxAndTransactionCostsDotDecimal),
                    .Description = paymentDescription,
                    .RedirectUrl = paymentRedirectUrl
}

        Select Case pymt
            Case GlobalFunctions.PaymentOption.CreditCard
                paymentRequest.Method = Mollie.Api.Models.Payment.PaymentMethod.CreditCard
            Case GlobalFunctions.PaymentOption.iDeal
                paymentRequest.Method = Mollie.Api.Models.Payment.PaymentMethod.Ideal
            Case GlobalFunctions.PaymentOption.GooglePay
                paymentRequest.Method = Mollie.Api.Models.Payment.PaymentMethod.GooglePay
        End Select

        Dim paymentResponse As PaymentResponse = Await paymentClient.CreatePaymentAsync(paymentRequest)
```

Other payment options do function correctly.

**Comment by Viincenttt** [comment]
Hi @neo1992 ,

I've just tried to create a Google Pay payment and I'm running into the same issue on the test environment. I've reached out to Mollie regarding this error and am currently awaiting their response. I'll reopen the issue until we get an answer :)

Thanks for reporting this issue!

**Comment by neo1992** [comment]
Hi @Viincenttt  4 months later and Mollie still doesn't seem to have fixed it, correct?

**Comment by neo1992** [comment]
@Viincenttt . Thanks. That page still shows "Google Pay is currently available only on the Mollie Hosted Checkout.", which is quite annoying tbh

**Comment by Viincenttt** [comment]
Hi @neo1992 ,

That is good feedback. I recommend that you mention this feedback to the Mollie development team. The easiest way to do this is to use the Mollie developer Discord. You can join using [this](https://discord.gg/Pdy49HxCWZ) link.
